name: CI-CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            
            echo "🚀 Starting deployment..."

            # Move to project directory
            cd /home/ubuntu/AI-Resume-Screening

            # Ensure repo is clean and updated
            git fetch origin main
            git reset --hard origin/main

            # Install dependencies (safe even if unchanged)
            source env/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt

            # Restart systemd service (IMPORTANT PART)
            sudo systemctl daemon-reload
            sudo systemctl restart streamlit

            # Check status (for debugging logs)
            sudo systemctl status streamlit --no-pager

            echo "✅ Deployment completed successfully"
