name: CI-CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/AI-Resume-Screening-System

            # 1. Wipe local changes and force sync with GitHub
            git fetch --all
            git reset --hard origin/main

            # 2. Activate environment and update packages
            source env/bin/activate
            pip install -r requirements.txt

            # 3. Force-kill old Streamlit instances without needing sudo permissions
            echo "Clearing out old application processes..."
            pkill -9 -u ubuntu -f "streamlit run" || true
            
            # 4. Give the operating system a moment to drop the connection
            sleep 3

            # 5. Start the new code on a clean, single line
            echo "Launching DevOps AI Screening V2.0..."
            nohup streamlit run webapp.py --browser.serverAddress 51.21.194.210 --server.address 0.0.0.0 --server.port 8501 > streamlit.log 2>&1 &
