name: CI-CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/AI-Resume-Screening-System

            # 1. Force pull clean code from GitHub
            git fetch --all
            git reset --hard origin/main

            # 2. Activate virtual environment and update packages
            source env/bin/activate
            pip install -r requirements.txt

            # 3. Kill any existing Streamlit apps safely
            echo "Stopping older version..."
            pkill -9 -f "streamlit run" || true
            
            # 4. Short buffer to let the OS release port 8501
            sleep 2

            # 5. The Bulletproof Launch (Forces background persistence)
            echo "Launching App Version 2.0..."
            nohup env/bin/streamlit run webapp.py --browser.serverAddress 51.21.194.210 --server.address 0.0.0.0 --server.port 8501 > streamlit.log 2>&1 < /dev/null &
            
            # 6. Verify it actually stayed alive for a second before dropping connection
            sleep 2
            ps aux | grep webapp.py
